obj-y += ddrc_r1p0.o bist.o ddrc_r1p0_common.o ddrc_r1p0_ctrl_init.o ddrc_r1p0_lpddrx.o ddrc_r1p0_phy_cfg.o ddrc_r1p0_phy_init.o \
    sharkl3_ddr_reinit.o \
    sharkl3_common.o \
    serial.o	\
    ddrc_r1p0_power_consumption.o
